### ISSUE TITLE
Using in modelform/out side django admin?

### ISSUE THREAD

**Issue by alzearafat** [douglasmiranda/django-wysiwyg-redactor#150]
Hi there!

Very nice plugin, and works like charm in django admin. But I wonder, how I can implement the editor also in modelforms? So I can display it to my user/front-end. I cannot find any docs for that.

Any help would be greatly appreciated! :)

Thank you

**Comment by dtkahl** [comment]
I have been facing the same problem recently.

According to [the django documentation](https://docs.djangoproject.com/en/1.10/topics/forms/media/), you can load needed CSS and JS files by adding this to your template: `{{ form.media }}`

It is important to included jQuery by your own, because redactor needs jQuery but the form field does not not include it in `form.media`.

see also http://stackoverflow.com/questions/1558533/django-widget-media-doesnt-work

**Comment by alzearafat** [comment]
@dtkahl 

Thank you for the clue! :)

Thanks
