### ISSUE TITLE
correct way to customize the toolbar

### ISSUE THREAD

**Issue by luzfcb** [douglasmiranda/django-wysiwyg-redactor#97]
Hello, what is the correct way to customize the redactor toolbar, changing on model field or globally (on settings.py)

**Comment by douglasmiranda** [comment]
I prefer on the model field, because some fields you'll probably want image upload , for example, some others fields you'll not want this feature.

If you make the customizations on the settings it will be a global change, so if this is what you want, good.

Sometimes you'll want to use both, applying the global changes, project wide, and make some customizations on each specific field that deviate from the project settings.
